module.exports = {
  TENANTS:
    [
      {
        firstName: 'Carolina',
        lastName: 'Pakra',
        checkIn: '01-jan-2020',
        checkOut: '01-june-2020',
        userId: '1',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Juncal 324',
        floor: '4to',
        door: '1ª',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'carito@hotmail.com',
        tel: '0054 679 123 456',
      },
      {
        firstName: 'Julen',
        lastName: 'Cima Pakra',
        checkIn: '01-jul-2020',
        checkOut: '31-Dec-2021',
        userId: '2',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Añasco 240',
        floor: 'PB',
        door: '1',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'julen@hotmail.com',
        tel: '+54 679 123 456',
      },
      {
        firstName: 'Ari',
        lastName: 'Cima',
        checkIn: '01-jul-2022',
        checkOut: '30-Aug-2022',
        userId: '3',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Parral 240',
        floor: '7mo',
        door: 'A',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'ari@hotmail.com',
        tel: '+54 679 123 456',
      },
      {
        firstName: 'Agus',
        lastName: 'Deluca',
        checkIn: '01-Jan-2021',
        checkOut: '30-Aug-2021',
        userId: '4',
        roomNr: 2,
        rent: '450',
        deposit: '450',
        address: 'Ramón Falcón 714',
        floor: '3ro',
        door: '4to',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'agus@hotmail.com',
        tel: '+54 222 123 456',
      },
      {
        firstName: 'Sebastian',
        lastName: 'Rosenthal',
        checkIn: '01-jul-2020',
        checkOut: '31-Dec-2021',
        userId: '5',
        roomNr: 3,
        rent: '300',
        deposit: '300',
        address: 'Añasco 240',
        floor: 'PB',
        door: '1',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'sebas@hotmail.com',
        tel: '+54 679 123 456',
      },
      {
        firstName: 'Damián',
        lastName: 'Cohen',
        checkIn: '01-jul-2020',
        checkOut: '31-Dec-2021',
        userId: '6',
        roomNr: 4,
        rent: '300',
        deposit: '300',
        address: 'Añasco 240',
        floor: 'PB',
        door: '1',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'dami@hotmail.com',
        tel: '+54 679 123 456',
      },
    ],
  SINGLE_ROOM_TENANTS:
    [
      {
        firstName: 'Carolina',
        lastName: 'Pakra',
        checkIn: '01-jan-2020',
        checkOut: '01-june-2020',
        userId: '1',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Juncal 324',
        floor: '4to',
        door: '1ª',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'carito@hotmail.com',
        tel: '0054 679 123 456',
      },
      {
        firstName: 'Julen',
        lastName: 'Cima Pakra',
        checkIn: '01-jul-2020',
        checkOut: '31-Dec-2020',
        userId: '2',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Añasco 240',
        floor: 'PB',
        door: '1',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'julen@hotmail.com',
        tel: '+54 679 123 456',
      },
      {
        firstName: 'Ari',
        lastName: 'Cima',
        checkIn: '01-jul-2022',
        checkOut: '30-Aug-2022',
        userId: '3',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Parral 240',
        floor: '7mo',
        door: 'A',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'ari@hotmail.com',
        tel: '+54 679 123 456',
      },
      {
        firstName: 'Agus',
        lastName: 'Deluca',
        checkIn: '01-Jan-2021',
        checkOut: '30-Aug-2021',
        userId: '4',
        roomNr: 1,
        rent: '450',
        deposit: '450',
        address: 'Ramón Falcón 714',
        floor: '3ro',
        door: '4to',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'agus@hotmail.com',
        tel: '+54 222 123 456',
      },
      {
        firstName: 'Sofi',
        lastName: 'Deluca',
        checkIn: '01-Sep-2021',
        checkOut: '31-Dec-2021',
        userId: '5',
        roomNr: 3,
        rent: '450',
        deposit: '450',
        address: 'Ramón Falcón 714',
        floor: '3ro',
        door: '4to',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'agus@hotmail.com',
        tel: '+54 222 123 456',
      },
      {
        firstName: 'Flor',
        lastName: 'Cima',
        checkIn: '01-Jan-2022',
        checkOut: '31-May-2022',
        userId: '6',
        roomNr: 1,
        rent: '450',
        deposit: '450',
        address: 'Ramón Falcón 714',
        floor: '3ro',
        door: '4to',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'agus@hotmail.com',
        tel: '+54 222 123 456',
      },
    ],
  COLORS: {
    GRAY: '#CCC5B9',
    GREENS: {
      FONTS: {
        TEXTS: '#264653',
        TITLES: '#184E77',
        NAV: '#264653',
        NAVHOV: '#52B69A',
      },
      BORDERS: {
        BLUE: '#168AAD',
        BORDHOV: '#52B69A',
        CANCEL: '#CCC5B9',
      },
      BUTTONS: {
        BACK: '#76C893',
        BACKHOV: '#52B69A',
        CANCELHOV: '#B7AD9C',
      },
    },
  },
};
