module.exports = {
  TENANTS:
    [
      {
        firstName: 'Carolina',
        lastName: 'Pakra',
        checkIn: '01-jan-2020',
        checkOut: '01-june-2020',
        userId: '1',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Juncal 324',
        floor: '4to',
        door: '1ª',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'carito@hotmail.com',
        tel: '0054 679 123 456',
      },
      {
        firstName: 'Julen',
        lastName: 'Cima Pakra',
        checkIn: '01-jul-2020',
        checkOut: '31-Dec-2020',
        userId: '2',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Añasco 240',
        floor: 'PB',
        door: '1',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'julen@hotmail.com',
        tel: '+54 679 123 456'
      },
      {
        firstName: 'Ari',
        lastName: 'Cima',
        checkIn: '01-jul-2022',
        checkOut: '30-Aug-2022',
        userId: '3',
        roomNr: 1,
        rent: '300',
        deposit: '300',
        address: 'Parral 240',
        floor: '7mo',
        door: 'A',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'ari@hotmail.com',
        tel: '+54 679 123 456'
      },
      {
        firstName: 'Agus',
        lastName: 'Deluca',
        checkIn: '01-Jan-2021',
        checkOut: '30-Aug-2021',
        userId: '4',
        roomNr: 2,
        rent: '450',
        deposit: '450',
        address: 'Ramón Falcón 714',
        floor: '3ro',
        door: '4to',
        city: 'Buenos Aires',
        country: 'Argentina',
        email: 'agus@hotmail.com',
        tel: '+54 222 123 456',
      },
    ],
};
